os: linux

language: go

go:
- 1.13.x

services:
- docker

script:
- go test -v ./...
- CGO_ENABLED=0 go build -o demo

- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin

- docker build -f Dockerfile -t ashiwalv/demo:latest ./

- GIT_SHA="$(git rev-parse --short HEAD)"
- docker tag ashiwalv/demo:latest ashiwalv/demo:$GIT_SHA

- docker push ashiwalv/demo:latest
- docker push ashiwalv/demo:$GIT_SHA
